### ISSUE TITLE
std::optional #include missing from SerializeJson-cpp17.h

### ISSUE THREAD

**Issue by davegorst** [jgaa/restc-cpp#117]
When compiling with standard set as c++17 just started getting this : 

/usr/local/include/restc-cpp/SerializeJson-cpp17.h:253:25: error: ‘optional’ is not a member of ‘std’
  253 | struct is_optional<std::optional<T> > {
  
  Adding the #include seems to fix it.

**Comment by jgaa** [comment]
logip compiles with C++14, C++17 and C++20 in CI. 
So closing this.
