### ISSUE TITLE
[FR] Bind source address.

### ISSUE THREAD

**Issue by gou4shi1** [jgaa/restc-cpp#122]
I need to call [bind()](https://www.boost.org/doc/libs/1_47_0/doc/html/boost_asio/reference/basic_stream_socket/bind.html) on the underlying scoket to send requests from a specific NIC.

**Comment by jgaa** [comment]
I guess that can be added to the client properties. 
I'll take a look at it.

**Comment by gou4shi1** [comment]
> I guess that can be added to the client properties.

I think so :)

> I guess that can be added to the client properties. I'll take a look at it.

Thanks!

**Comment by jgaa** [comment]
I have created a branch for the bind support. It seems to work, but I will test it a little more before I merge it to master.

https://github.com/jgaa/restc-cpp/tree/bind-support

**Comment by gou4shi1** [comment]
Great! I will test this ASAP. Thank you very much :)
