### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by juansebastiani2cat** [jgaa/restc-cpp#124]
I have built the library (With several of the tests failing) and then I created a simple hello world project: 

```
#include <iostream>
#include <boost/lexical_cast.hpp>
#include <boost/fusion/adapted.hpp>
#include </home/i2cat/Downloads/restc-cpp/include/restc-cpp/restc-cpp.h>
#include </home/i2cat/Downloads/restc-cpp/include/restc-cpp/SerializeJson.h>
#include </home/i2cat/Downloads/restc-cpp/include/restc-cpp/RequestBuilder.h>
using namespace std;
int main() {
	cout << "!!!Hello World!!!" << endl; // prints !!!Hello World!!!
	return 0;
}
```

But on the compilation stage, the following error appears: 

![image](https://user-images.githubusercontent.com/85935421/162261566-662f5933-678f-4e0a-a295-a5a8fbd727e7.png)

I am running Ubuntu 20.04 LTS

**Comment by jgaa** [comment]
When you build the library with *cmake*, `config.h` is created and contains the relevant build options needed to use the other headers with the compiled library. It is important to make sure to either install or include the project in a way where this file is preserved.

For example, in `k8deployer` I use restc-cpp as an included cmake project. You can see how that is done here:
https://github.com/jgaa/k8deployer/blob/820d4844d485f3e6d323cd23684b4e6551d4d599/cmake/external-projects.cmake#L12

Regarding the tests, only the unit-tests will pass unless you have *docker-compose* installed and [start the functional test back-end suite](https://github.com/jgaa/restc-cpp/blob/master/create-and-run-containers.sh).
