### ISSUE TITLE
provide build package for MSVC via vcpkg

### ISSUE THREAD

**Issue by danyhm** [jgaa/restc-cpp#131]
Hello,

I'm trying to build restc-cpp on windows and like everyone else I'm stumbling upon build issue.
one thing i noticed that probably makes all problems go away is using vcpkg for dependencies. since your project depends on boost and zlib and both are available via vcpkg it shouldn't be a problem making a cmake file for it.

I don't know how to do that , else i'd have opened a PR.

**Comment by danyhm** [comment]
I tried to make a build file using vcpkg. it detects openssl and zlib. however for boost it seems some extra parameters should be added. I couldn't figure out them yet.
so far in build_vc2017.bat change the cmake line to
`cmake -DBoost_DEBUG=ON -DCMAKE_TOOLCHAIN_FILE=C:/dev/vcpkg/scripts/buildsystems/vcpkg.cmake -G "Visual Studio 16 2019" ..`

-DCMAKE_TOOLCHAIN_FILE should point to your vcpkg.cmake path

**Comment by danyhm** [comment]
finally managed to make it using vcpkg. it's pretty straightforward.

./vcpkg install boost zlib openssl
and then run the bat file using VS command prompt

**Comment by jgaa** [comment]
Thank you for the build script.

There is also a simple example in the jenkins CI definition to use vcpkg in to get the dependencies. 
https://github.com/jgaa/restc-cpp/blob/47f08d760741a9b24ceec04a5da6237706540cbb/ci/jenkins/Jenkinsfile.groovy#L690
