### ISSUE TITLE
Build failed with Boost 1.86

### ISSUE THREAD

**Issue by Osyotr** [jgaa/restc-cpp#160]
I'm updating Boost in vcpkg (https://github.com/microsoft/vcpkg/pull/40465) and the package `restc-cpp` fails to build.
Please see the attached log.

[install-x64-linux-dbg-out.log](https://github.com/user-attachments/files/17090912/install-x64-linux-dbg-out.log)

**Comment by jgaa** [comment]
I think I have fixed the problem. The changes are in the `staging` branch.

I'm currently running the automation tests on all the supported platforms.

**Comment by jgaa** [comment]
Changes were merged to master branch.

**Comment by Osyotr** [comment]
@jgaa regarding the fix, I think you can remove the hack by just passing `{}` as the third parameter.
https://godbolt.org/z/Ts8foT86x
And it also looks like that the other overload (i.e. the one that takes `boost::coroutines::attributes`) used to be selected in previous versions.
