### ISSUE TITLE
How to get server response code on exception?

### ISSUE THREAD

**Issue by arteniioleg** [jgaa/restc-cpp#26]
I am using this library to test my REST server.

I want to create a test that will fail on purpose and the server response code must be `4xx` (or `401` Unauthorized).

I don't know how to achieve that because any server response that is not 200 is considered fail and this library throws an exception. The exception has only the error message `e.what()` without details about the fail (in my case I need server response code)

```cpp
auto restClient = RestClient::Create();
std::unique_ptr<Reply> reply;

restClient->Process([&reply](Context& ctx){
    try {
        reply = ctx.Get("http://localhost/");
    } catch (const std::exception& e) {
        // I need server response code here
    }
});
restClient->CloseWhenReady(true);
```

**Comment by jgaa** [comment]
Hi, sorry for the late reply.

The exception derives from restc_cpp::RequestFailedWithErrorException. This structure contains a member variable,  .http_response of type restc_cpp::Reply::HttpResponse that contains information about the error.

```c++
auto restClient = RestClient::Create();
std::unique_ptr<Reply> reply;

restClient->Process([&reply](Context& ctx){
    try {
        reply = ctx.Get("http://localhost/");
    } catch (const restc_cpp::RequestFailedWithErrorException& e) {
        // I need server response code here
        cout << "Server error response: " << e.http_response.status_code << endl;
    }
});
restClient->CloseWhenReady(true);
```
Check out
