### ISSUE TITLE
Deserialize a struct conatins a vector<string>

### ISSUE THREAD

**Issue by dheeraj12190** [jgaa/restc-cpp#31]
I am using restc-cpp api. and facing below issue 
my rest API is giving below response
```C++
[
  {
    "id": 1,
    "MeterNo": "100101",
    "Status": 0,
    "Services": ["service1","service2","service3"]
  },
  {
    "id": 2,
    "MeterNo": "100102",
    "Status": 0,
    "Services": "Services": ["service1","service2","service3"]
  }
]
```
I am using these structures to Serialize  
```C++
struct Schedule
{    
    int id;
    string MeterNo;
    int Status;
    vector<string> Services;
};
BOOST_FUSION_ADAPT_STRUCT
(
        Schedule,
        (int, id)
        (string, MeterNo)
        (int, Status)
        (vector<string>, Services)
)
```
it gives very big compilation error where using Function SerializeFromJson(). 
can you help?
Thanks in Advance.

**Comment by jgaa** [comment]
You probably need to use <code>std::vector</code>, as <code>BOOST_FUSION_ADAPT_STRUCT</code> require full name-space declaration.
