### ISSUE TITLE
C++17 build

### ISSUE THREAD

**Issue by VikingExplorer** [jgaa/restc-cpp#33]
Trying to use this library as part of a c++17 project.

Getting: restc-cpp/helper.h(23): error C2039: 'binary_function': is not a member of 'std'

it's deprecated.  According to the stackoverflow link in the file, it can just be removed:

`struct ciLessLibC //: public std::binary_function<std::string, std::string, bool> 
`

**Comment by jgaa** [comment]
What compiler are you using?
I cannot reproduce the problem with g++ 7.2.0 under Debian testing

**Comment by VikingExplorer** [comment]
Visual Studio 2017 - PRO, 15.5.2
Language setting (/std:c++17)

**Comment by jgaa** [comment]
I can reproduce with msvc. 
I have to recompile boost, so I will probably commit a fix when it's tested tomorrow.
