### ISSUE TITLE
Compile issues on Ubuntu 16.04

### ISSUE THREAD

**Issue by harishom** [jgaa/restc-cpp#34]
Hi I get following errors while compiling in Ubuntu 16.04 LTS. Any idea how these can be fixed?

[ 45%] Linking CXX executable ../bin/simplewriter
[ 45%] Built target simplewriter
Scanning dependencies of target examples
[ 45%] Built target examples
Scanning dependencies of target archivertest
[ 46%] Building CXX object example/CMakeFiles/archivertest.dir/archiver/archiver.cpp.o
In file included from /root/restc-cpp/dbuild/external-projects/src/externalRapidJson/example/archiver/archiver.cpp:1:0:
/root/restc-cpp/dbuild/external-projects/src/externalRapidJson/example/archiver/archiver.h:56:7: error: 'class JsonReader' has pointer data members [-Werror=effc++]
 class JsonReader {
       ^
/root/restc-cpp/dbuild/external-projects/src/externalRapidJson/example/archiver/archiver.h:56:7: error:   but does not override 'JsonReader(const JsonReader&)' [-Werror=effc++]
/root/restc-cpp/dbuild/external-projects/src/externalRapidJson/example/archiver/archiver.h:56:7: error:   or 'operator=(const JsonReader&)' [-Werror=effc++]
/root/restc-cpp/dbuild/external-projects/src/externalRapidJson/example/archiver/archiver.h:100:7: error: 'class JsonWriter' has pointer data members [-Werror=effc++]
 class JsonWriter {
       ^

**Comment by jgaa** [comment]
Fixed.
Thanks for reporting the issue.
