### ISSUE TITLE
Impossible to access all `Set-Cookie` headers

### ISSUE THREAD

**Issue by arteniioleg** [jgaa/restc-cpp#37]
In response I have [multiple cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie) but `Reply::GetHeader(name)` returns only the last header with the give name

https://github.com/jgaa/restc-cpp/blob/6398d70c772cc857c50d0ea4add8acfe85ccd10b/include/restc-cpp/restc-cpp.h#L226-L228

Until this will be fixed, any workaround?

**Comment by arteniioleg** [comment]
I just found that [restbed](https://github.com/Corvusoft/restbed) has a http client (this is my workaround).
Much simpler to use and has a `get_headers()` method that returns a `multimap`.

```cpp
std::string uri {"http://localhost/test"};
std::string body {"{\"foo\":\"bar\"}"}

auto request = std::make_shared<restbed::Request>(restbed::Uri{uri});
request->set_method("POST");
request->set_headers({{"Content-Length", std::to_string(body.size())}});
request->set_body(body);

auto response {restbed::Http::sync(request)};

auto cookieHeaders {response->get_headers("Set-Cookie")};

std::string responseBody {
    restbed::String::to_string(
        restbed::Http::fetch(
            std::stoi(response->get_header("Content-Length")), 
            response
        )
    )
};
```

**Comment by jgaa** [comment]
I have not implemented dedicated support for cookies yet. It will be done soon. The last few weeks I have worked on another project, including some Jenkins CI work.
Currently it's too much work to test new features on all the platforms I support with restc-cpp. That has held the progress back. 
One of the next days I will setup automatic builds and tests for all the platforms supported, and after that I will fix the bugs and move the project forward.

**Comment by arteniioleg** [comment]
> I have not implemented dedicated support for cookies yet.

I haven't asked support for cookies. It's just an example of multi-header value.

**Comment by jgaa** [comment]
Yes, I'll fix that as well :)
Cookies has been on my list for a while, I just never needed it myself.
