### ISSUE TITLE
Add `RequestBuilder::Options(url)`

### ISSUE THREAD

**Issue by arteniioleg** [jgaa/restc-cpp#38]
https://github.com/jgaa/restc-cpp/blob/6398d70c772cc857c50d0ea4add8acfe85ccd10b/include/restc-cpp/RequestBuilder.h#L42-L76

I need to create an `OPTIONS` request ([Preflighted requests](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS#Preflighted_requests))

**Comment by arteniioleg** [comment]
I see methods are hardcoded and `OPTIONS` is not included

https://github.com/jgaa/restc-cpp/blob/6398d70c772cc857c50d0ea4add8acfe85ccd10b/include/restc-cpp/restc-cpp.h#L112-L117

----

http://zacstewart.com/2012/04/14/http-options-method.html

> #### What is the HTTP OPTIONS method?
> To quote the spec:
>
> > This method allows the client to determine the options and/or requirements associated with a resource, or the capabilities of a server, without implying a resource action or initiating a resource retrieval.

**Comment by jgaa** [comment]
I agree. Options needs to be there.
