### ISSUE TITLE
LInking errors

### ISSUE THREAD

**Issue by jdiaz4517** [jgaa/restc-cpp#48]
Hello
I use CLion as my IDE. I've been trying to run some of the tests (basic_tests, crud_tests) as well as some of the examples, just trying to get familiar with the code, but I keep getting the same error all the time:
Undefined symbols for architecture x86_64:
  "_SSL_COMP_free_compression_methods", referenced from:
      boost::asio::ssl::detail::openssl_init_base::do_init::~do_init() in librestc-cppD.a(ConnectionPoolImpl.cpp.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Do I need to change some of the CMakeList.txt to add some -l... options?

Thanks
Javier

**Comment by jgaa** [comment]
If you use the cmakefile supplied with the project, it will require openssl, and add add the linker flags to link with the openssl libraries. If this is what you are doing, what operating system are you using?

Jarle

**Comment by jdiaz4517** [comment]
Hi Jarle
It's all ok now.  It was just some settings needed to get thing working from inside CLion.

Thanks
Javier

**Comment by jgaa** [comment]
Thank you for the update :)
