### ISSUE TITLE
Error while Make

### ISSUE THREAD

**Issue by thefiend** [jgaa/restc-cpp#49]
Hi, I get the following error when I try to Make. Wish to know how to resolve this. Thanks!!!
<img width="823" alt="screen shot 2018-03-09 at 12 05 30 pm" src="https://user-images.githubusercontent.com/3714496/37190006-3829fefa-2392-11e8-85be-abcb51f1ab4a.png">

**Comment by jgaa** [comment]
Hi, this means that the linker don't find the openssl library.

This works on my mac:
```sh
brew install openssl boost zlib cmake
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DBOOST_LIBRARIES=/usr/local/opt/boost/lib -DBOOSTL_ROOT_DIR=/usr/local/opt/boost -DZLIB_INCLUDE_DIRS=/usr/local/opt/zlib/include/ -DZLIB_LIBRARIES=/usr/local/opt/zlib/lib/ ..
```

**Comment by thefiend** [comment]
Hi, I am trying to add restc-cpp into my CLion project. However,  I get 
"fatal error: 'restc-cpp/helper.h' file not found"
even after including it in my code. Any idea how to resolve this?

**Comment by jgaa** [comment]
I have never used CLion.

However, the error indicate that you need to add the include path(s) required by restc to your project. If you "make install" restc-cpp, the includes should be installed in /usr/local/include/restc-cpp, so all you have to do is to add  /usr/local/include/ to the include paths for your project.

**Comment by thefiend** [comment]
<img width="694" alt="screen shot 2018-03-11 at 11 03 04 am" src="https://user-images.githubusercontent.com/3714496/37249121-ecb63340-251b-11e8-95d4-50f42a89bbbe.png">
I am still getting this error after I **make -j4**

**Comment by jgaa** [comment]
This means that the path to the openssl libraries is incorrect or unset.

If you installed it with 'brew install', it should be in 

```sh
jarles-Mac-mini:~ jgaa$ ls /usr/local/opt/openssl/lib
engines                 libcrypto.a             libssl.1.0.0.dylib      libssl.dylib
libcrypto.1.0.0.dylib   libcrypto.dylib         libssl.a                pkgconfig
```
If it's there, make sure to run cmake with '-DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib'. If it's not there, you must locate the libraries and set the LIBRARIES path accordingly.

When I run cmake on my mac, I see this in the output:
```
jgaa$ cmake -DCMAKE_BUILD_TYPE=Release -DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib -DBOOST_LIBRARIES=/usr/local/opt/boost/lib -DBOOSTL_ROOT_DIR=/usr/local/opt/boost -DZLIB_INCLUDE_DIRS=/usr/local/opt/zlib/include/ -DZLIB_LIBRARIES=/usr/local/opt/zlib/lib/ ..

-- Found OpenSSL: /usr/local/opt/openssl/lib/libcrypto.dylib (found version "1.0.2n")
```
Make sure that you feed cmake with the correct locations to the libraries (boost, openssl and zlib).

You can run 
```sh
make VERBOSE=1
```
to see the full output from make. This will show the full command-line to the linker, including libraries and paths to search.

**Comment by thefiend** [comment]
Hi, got it working thanks!!!!
