### ISSUE TITLE
Error linking http_reply_tests during make

### ISSUE THREAD

**Issue by codeWonderland** [jgaa/restc-cpp#60]
![image](https://user-images.githubusercontent.com/22084929/39002325-45f96fc6-43c6-11e8-9e81-f7d576bcf58c.png)
I'm getting the following error during make while on Linux. Any ideas?

**Comment by jgaa** [comment]
The errors refer to missing openssl symbols. What operating system are you using? 

Also, can you show me the output from cmake when it discovers opsnssl? On my dev machine that looks like "-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.0f")"

The output from this command, from the build directory, is also interesting:
```sh
cmake -LAH .. | grep OPEN
```
