### ISSUE TITLE
Include headers in RequestFailedWithErrorException

### ISSUE THREAD

**Issue by gdfast** [jgaa/restc-cpp#62]
I can see that `ValidateReply()` is called on a reply in `RequestImpl.cpp`'s `GetReply(Context&)`, and if the result's `status_code` falls outside of accepted range, the appropriate `RequestFailedWithErrorException` is thrown.

However, `RequestFailedWithErrorException` only includes the reply's `HttpResponse`, which may be excluding some very useful information. It would be really helpful if **headers** could also be included in the `RequestFailedWithErrorException`.

Specifically, I am using _restc-cpp_ to build a C++ InfluxDB client, but cannot access useful error information that the influxdb server returns in the headers. Here's a clip from python using [requests](http://docs.python-requests.org/en/master/) to illustrate the point

```python
In [1]: import requests

In [2]: result = requests.get('http://localhost:8086/query?q=hi')

In [3]: result.headers
Out[3]: {'Content-Type': 'application/json', 'Request-Id': 'de181314-4cbb-11e8-8063-000000000000', 'X-Influxdb-Build': 'OSS', 'X-Influxdb-Error': 'error parsing query: found hi, expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1', 'X-Influxdb-Version': '1.5.2', 'X-Request-Id': 'de181314-4cbb-11e8-8063-000000000000', 'Date': 'Mon, 30 Apr 2018 21:17:20 GMT', 'Content-Length': '147'}

In [4]: result.headers['X-Influxdb-Error']
Out[4]: 'error parsing query: found hi, expected SELECT, DELETE, SHOW, CREATE, DROP, EXPLAIN, GRANT, REVOKE, ALTER, SET, KILL at line 1, char 1'

In [5]: result.status_code
Out[5]: 400

In [6]: result.reason
Out[6]: 'Bad Request'
```

I basically want to write code similar to:
```C++
void onError(const RequestFailedWithErrorException& httpError)
{
    auto influxErrorMessage = httpError.GetHeader("X-Influxdb-Error");
    if (influxErrorMessage)
    {
        MyLogger(error) << "Here's what went wrong: " << *influxErrorMessage;
    }
    
}
```

(Thanks!)

**Comment by asgeo1** [comment]
+1 for this.  Both headers *and* the body should be available.

I've got an endpoint that is returning a 400 error, with JSON formatted error in the body.

I've got no way to read the body that I can see?

**Comment by jgaa** [comment]
That's actually a very good point.
