### ISSUE TITLE
no config.h in include folder

### ISSUE THREAD

**Issue by Mamlesh** [jgaa/restc-cpp#63]
there is no config.h folder in include folder ...
and where do i find libboost_system-vc140-mt-gd-x64-1_67.lib library ...
pls help

**Comment by jgaa** [comment]
The config-file is generated by cmake when it configures the build.

Regarding boost - you need to download and build the boost libraries, openssl and zlib, and place them somewhere. [build_vc2017.bat](https://github.com/jgaa/restc-cpp/blob/master/build_vc2017.bat) shows how to tell cmake where to find these files on my build server. These libraries are not embedded in the restc-cpp build, and must exist before you can build restc-cpp.
