### ISSUE TITLE
Make an opption to totally disable logging

### ISSUE THREAD

**Issue by jgaa** [jgaa/restc-cpp#67]
Also make it trivial to provide log-macros to enable other log methods.

**Comment by KingDuckZ** [comment]
Is there a fix for this? Logging is so verbose it's making my tool unusable

**Comment by KingDuckZ** [comment]
Can I get some help with this please?

**Comment by jgaa** [comment]
I'm working on it.

**Comment by jgaa** [comment]
Disabling logs are implemented in the `work` branch. You can try it. 
I have not merged it to master because my test infrastructure is off-line, and I don;'t want to break anything.

**Comment by KingDuckZ** [comment]
Thank you for looking into this! :)
