### ISSUE TITLE
Why suppress tlsv1_1 while BOOST_VERSION >= 105900?

### ISSUE THREAD

**Issue by liangyulai** [jgaa/restc-cpp#68]
Hi,

I see the tlsv1.1 was suppressed while boost version > 1.59, is there any reason on this?

I ask this because I had test this project locally, I expect it will send ssl handshake with tlsv1.2, but it send a ssl handshake with tlsv1.0 instead.

And my toolchain is:
-- The C compiler identification is GNU 7.3.0
-- The CXX compiler identification is GNU 7.3.0
-- Found OpenSSL: 1.1.0g
-- Boost version: 1.62.0

[TlsSocketImpl.h](https://github.com/jgaa/restc-cpp/blob/master/src/TlsSocketImpl.h)

```
#if BOOST_VERSION >= 105900
            | boost::asio::ssl::context::no_tlsv1_1
#endif
```

Comment out this will solve my problem, but I would like to know the reason about your implementation.

Thanks.

BR/Yulai

**Comment by jgaa** [comment]
Honestly I don't recall why. Most likely this was a quick fix to get around a build problem at some time. Boost/openssl has is a fragile couple.

**Comment by liangyulai** [comment]
Thanks, Jgaa.

I will let it go for now, as the OpenSSL code is too complicate. :(
