### ISSUE TITLE
SSL Implementation

### ISSUE THREAD

**Issue by rhard** [jgaa/restc-cpp#74]
I found there is no way to configure SSL parameters of the connection. Do you plan to implement this?

What I actually need is:

1. possibility to set CA certificate (not use a system pool)
2. possibility to set client certificate and private key
3. change some connection policies

I would try to contribute myself. The boost asio already has all needed methods so I need to change TlsSocketImpl.h.  But I don't know what interface should look like for the end user.

Also I don't know what is your plans generally. Without full SSL support the library usage is very limited.

I'v already tried cpprestsdk and Poco. Everywhere there are some limitations. Very disappointing there is no simple C++ library to provide secure HTTPS requests. Or should I go for the libcurl anyway?

**Comment by rhard** [comment]
Actually we need to give the user an access to the boost::asio::ssl::context inside RestClientImpl.cpp class.

I would prefer to construct ssl::context in the application code and pass it to the RastClient during initialization:
```C
boost::asio::ssl::context ctx(boost::asio::ssl::context::sslv23);
ctx.use_certificate("blablabla"):
auto rest_client = RestClient::Create(properties, ctx);
```
It will require:

1. Add ctx member to the RastClient
2. Add  RestClient::Create new overloaded function
3. TlsSocketImpl constructor change to 
```C
TlsSocketImpl(boost::asio::io_service& io_service, boost::asio::ssl::context &tls_options)
```
So tls context will be owned by RestClient. If user uses default constructor, the default tls context will be created.

Would you accept such patch?

**Comment by jgaa** [comment]
I would be happy to receive a patch for this.

**Comment by jgaa** [comment]
Sorry for the delay with the merge. I've been buried in another project for a while.
