### ISSUE TITLE
What about to Data(const char *)

### ISSUE THREAD

**Issue by Domest0s** [jgaa/restc-cpp#76]
Problem:

Calling builder.Data("{}") actually calls template version of Data(const T& data,...), not the Data(std::string &&)

Application stops only on assert() very deep in a call stack. Lost hours on debugging.

Please consider adding one more version of method Data() in RequestBuilder to accept one parameter of type const char *

**Comment by Domest0s** [comment]
Thank you!

**Comment by jgaa** [comment]
Thanks for reporting the issue!
