### ISSUE TITLE
No longer builds with latest Boost in Git after deprecated get_io_service removed

### ISSUE THREAD

**Issue by davegorst** [jgaa/restc-cpp#89]
Looks like IoReaderImpl.cpp relies on this :

/home/dgvm/restc-cpp/include/restc-cpp/IoTimer.h:112:49: error: ‘boost::asio::ip::tcp::socket’ {aka ‘class boost::asio::basic_stream_socket<boost::asio::ip::tcp>’} has no member named ‘get_io_service’
             connection->GetSocket().GetSocket().get_io_service(),
                                                 ^~~~~~~~~~~~~~

**Comment by davegorst** [comment]
Looks like it's no longer in 1.70 either : https://www.boost.org/doc/libs/1_70_0/doc/html/boost_asio/history.html

**Comment by jgaa** [comment]
They renamed it. I'll fix it.

**Comment by hoangtrucit** [comment]
i have sample issue
